openapi: 3.0.1
info:
  title: Yahalom Gateway API
  description: This is a restAPI service for 3d products
  version: 1.0.0
  license:
    name: Yahalom-Gateway repo link
    url: https://github.com/MapColonies/yahalom-gateway/
paths:
  /message:
    post:
      operationId: createMessage
      tags:
        - Message
      summary: Creates a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLogObject'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ILogObject'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    get:
      operationId: getMessages
      tags:
        - Message
      summary: Gets the messages filtered
      parameters:
        - name: sessionId
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: severity
          in: query
          required: false
          schema:
            type: string
            enum:
              - EMERGENCY
              - ALERT
              - CRITICAL
              - ERROR
              - WARNING
              - NOTICE
              - INFORMATIONAL
              - DEBUG
        - name: component
          in: query
          required: false
          schema:
            type: string
            enum:
              - GENERAL
              - MAP
              - FTUE
              - SIMULATOR
        - name: messageType
          in: query
          required: false
          schema:
            type: string
            enum:
              - APPSTARTED
              - APPEXITED
              - USERDETAILS
              - USERMACHINESPEC
              - USERDEVICES
              - DEVICECONNECTED
              - DEVICEDISCONNECTED
              - GAMEMODESTARTED
              - GAMEMODEENDED
              - IDLETIMESTARTED
              - IDLETIMEENDED
              - LAYERUSESTARTED
              - LAYERUSERENDED
              - MULTIPLAYERSTARTED
              - MULTIPLAYERENDED
              - LOCATION
              - ERROR
              - GENERALINFO
              - WARNING
              - CONSUMPTIONSTATUS
              - APPLICATIONDATA
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ILogObject'
        204:
          description: No content - no messages found
          content:
            application/json:
              schema:
                required:
                  - msg
                properties:
                  msg:
                    type: string
                    description: The message for integrating
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
security:
  - {}

components:
  schemas:
    error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: A human-readable error message
      example:
        error: 'Invalid message ID provided.'

    CreateLogObject:
      type: object
      required:
        - sessionId
        - severity
        - timeStamp
        - message
        - component
        - messageType
      properties:
        sessionId:
          type: integer
          format: int64
          description: Unique session identifier
        severity:
          type: string
          enum:
            - EMERGENCY
            - ALERT
            - CRITICAL
            - ERROR
            - WARNING
            - NOTICE
            - INFORMATIONAL
            - DEBUG
          description: Severity level of the log
        timeStamp:
          type: string
          format: date-time
          description: Timestamp of the log entry
        message:
          type: string
          description: Main message text
        messageParameters:
          type: array
          description: Additional info
        component:
          type: string
          enum:
            - GENERAL
            - MAP
            - FTUE
            - SIMULATOR
          description: The component generating the log
        messageType:
          type: string
          enum:
            - APPSTARTED
            - APPEXITED
            - USERDETAILS
            - USERMACHINESPEC
            - USERDEVICES
            - DEVICECONNECTED
            - DEVICEDISCONNECTED
            - GAMEMODESTARTED
            - GAMEMODEENDED
            - IDLETIMESTARTED
            - IDLETIMEENDED
            - LAYERUSESTARTED
            - LAYERUSERENDED
            - MULTIPLAYERSTARTED
            - MULTIPLAYERENDED
            - LOCATION
            - ERROR
            - GENERALINFO
            - WARNING
            - CONSUMPTIONSTATUS
            - APPLICATIONDATA
          description: Type/category of the message

    ILogObject:
      allOf:
        - $ref: '#/components/schemas/CreateLogObject'
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              description: Unique identifier of the log entry
