openapi: 3.0.1
info:
  title: Yahalom Gateway API
  description: D
  version: 1.0.0
  license:
    name: Yahalom-Gateway repo link
    url: https://youtube.com
paths:
  /message:
    post:
      operationId: createMessage
      tags:
        - Message
      summary: creates a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ILogObject'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ILogObject'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
security:
  - {}
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A human-readable error message
      example:
        message: 'Invalid message ID provided.'

    ILogObject:
      type: object
      required:
        - sessionId
        - severity
        - timeStamp
        - message
        - messageParameters
        - component
        - messageType
      properties:
        sessionId:
          type: integer
          format: int64
          description: Unique session identifier
        severity:
          type: string
          description: Severity level of the log
        timeStamp:
          type: string
          format: date-time
          description: Timestamp of the log entry
        message:
          type: string
          description: Main message text
        messageParameters:
          $ref: '#/components/schemas/IAnalyticLogParameter'
        component:
          type: string
          description: The component generating the log
        messageType:
          type: string
          description: Type/category of the message

    IAnalyticLogParameter:
      type: object
      additionalProperties:
        type: string
