openapi: 3.0.1
info:
  title: Yahalom Gateway API
  description: This is a restAPI service for 3d products
  version: 1.0.0
  license:
    name: Yahalom-Gateway repo link
    url: https://github.com/MapColonies/yahalom-gateway/
paths:
  /message:
    post:
      operationId: createMessage
      tags:
        - Message
      summary: creates a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ILogObject'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: integer
                    description: The ID of the created message
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    get:
      operationId: getMessages
      tags:
        - Message
      summary: gets the messages filtered
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ILogObject'
        204:
          description: No content - no messages found
          content:
            application/json:
              schema:
                required:
                  - msg
                properties:
                  msg:
                    type: string
                    description: The message for intergrating

        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

security:
  - {}
components:
  schemas:
    error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: A human-readable error message
      example:
        message: 'Invalid message ID provided.'

    ILogObject:
      type: object
      required:
        - sessionId
        - severity
        - timeStamp
        - message
        - component
        - messageType
      properties:
        sessionId:
          type: integer
          format: int64
          description: Unique session identifier
        severity:
          type: string
          enum:
            - EMERGENCY
            - ALERT
            - CRITICAL
            - ERROR
            - WARNING
            - NOTICE
            - INFORMATIONAL
            - DEBUG
          description: Severity level of the log
        timeStamp:
          type: string
          format: date-time
          description: Timestamp of the log entry
        message:
          type: string
          description: Main message text
        messageParameters: #Optional
          $ref: '#/components/schemas/IAnalyticLogParameter'
        component:
          type: string
          enum:
            - GENERAL
            - MAP
            - FTUE
            - SIMULATOR
          description: The component generating the log
        messageType:
          type: string
          enum:
            - APPSTARTED
            - APPEXITED
            - USERDETAILS
            - USERMACHINESPEC
            - USERDEVICES
            - DEVICECONNECTED
            - DEVICEDISCONNECTED
            - GAMEMODESTARTED
            - GAMEMODEENDED
            - IDLETIMESTARTED
            - IDLETIMEENDED
            - LAYERUSESTARTED
            - LAYERUSERENDED
            - MULTIPLAYERSTARTED
            - MULTIPLAYERENDED
            - LOCATION
            - ERROR
            - GENERALINFO
            - WARNING
            - CONSUMPTIONSTATUS
            - APPLICATIONDATA
          description: Type/category of the message

    IAnalyticLogParameter:
      type: array
      items: {}
