apiVersion: v2
name: yahalom-gateway
description: A Helm chart for yahalom-gateway service
type: application
version: 1.0.2
appVersion: 1.0.2

dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
